### ISSUE TITLE
Status Report page showing "Array Array" instead of actual setting information.

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#791]
On the Status Report page, after a clean install, an undefined row exists "Array  Array". I think this warning when running <code>drush rq</code> may be related: <code>wordwrap() expects parameter 1 to be string, array given output.inc:211</code>

![Status-report-_-OpenConcept-2013-03-20-11-53-15](https://f.cloud.github.com/assets/82974/281463/6ca8c29e-9178-11e2-9fd8-bd5e60a734fb.gif)

**Comment by sylus** [comment]
Good catch!

**Comment by sylus** [comment]
Fixed on master will be brought to 3.1 shortly.

**Comment by MikeDucharme** [comment]
Has this been brought to the 3.1 branch yet? I'm still seeing this error.
