### ISSUE TITLE
build issue ?

### ISSUE THREAD

**Issue by joejoseph00** [wet-boew/wet-boew-drupal#982]
drush version 5.4
PHP 5.3.5 (cli)
git version 1.7.3.4

Unable to patch caption_filter with 1432092-button-and-image.patch.                                                                                                               [error]

**Comment by joejoseph00** [comment]
today I get new build errors: 
From my SLES box I get these errors when doing a DRUSH MAKE:

Unable to patch caption_filter with 1432092-button-and-image.patch.                                                                                                               [error]

Unable to download https://drupal.org/files/deploy_new_alter_hook-2092335-2.patch.                                                                                                [error]

**Comment by sylus** [comment]
Not sure where you are cloning? Is this through msysgit? If so the patch command has problems depending on the version. The second error has been fixed.

**Comment by joejoseph00** [comment]
Hi @sylus, just trying a build today and I still get the second error.
Unable to download https://drupal.org/files/deploy_new_alter_hook-2092335-4.patch.                                                                                      [error]

**Comment by joejoseph00** [comment]
I'm using git 1.7.3.4 and I upgraded my drush to 6.0 , on top of php 5.3.5

I'm waiting for the build to finish, so far two errors, here's the second one (Unable to determine mime type for spyc.php.) :

spyc downloaded from https://raw.github.com/mustangostang/spyc/79f61969f63ee77e0d9460bc254a27a671b445f3/spyc.php.                                                       [ok]
Unable to determine mime type for spyc.php.                                                                                                                             [error]

**Comment by joejoseph00** [comment]
@sylus, so error messages come up three times, but two are the same 

Unable to download https://drupal.org/files/deploy_new_alter_hook-2092335-4.patch. [error]
Unable to determine mime type for spyc.php. [error]
Unable to download https://drupal.org/files/deploy_new_alter_hook-2092335-4.patch. [error](same as first error)

, still waiting for the drush make to complete

**Comment by joejoseph00** [comment]
@sylus  and another error:
Unable to patch caption_filter with 1432092-button-and-image.patch.                                                                                                     [error]

**Comment by Gale-ccohs** [comment]
@joejoseph00 I had this issue today: Unable to determine mime type for spyc.php.

It was resolved by editing  the php.ini file in the drush folder, and inserting the line 
extension=php_fileinfo
in the Dynamic Extensions section. It took me a while to wake up to the idea that there was more than one php.ini on the system, and the one in the drush folder needed changing as well.
